### ISSUE TITLE
verify.sh can cause controller to panic

### ISSUE THREAD

**Issue by rbradford** [ciao-project/ciao#1568]
Observed on memory limited (1GiB ccloudvm)

```
Nov 07 15:15:09 singlevm ciao-controller[23771]: 2017/11/07 15:15:09 http: panic serving 127.0.0.1:59368: runtime error: invalid memory address or nil pointer dereference
Nov 07 15:15:09 singlevm ciao-controller[23771]: goroutine 227 [running]:
Nov 07 15:15:09 singlevm ciao-controller[23771]: net/http.(*conn).serve.func1(0xc4204baf00)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /usr/local/go/src/net/http/server.go:1697 +0xd0
Nov 07 15:15:09 singlevm ciao-controller[23771]: panic(0x923720, 0xe08fe0)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /usr/local/go/src/runtime/panic.go:491 +0x283
Nov 07 15:15:09 singlevm ciao-controller[23771]: main.instanceToServer(0xc4200e0af0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /home/runner/test/src/github.com/ciao-project/ciao/ciao-controller/compute.go:33 +0x64
Nov 07 15:15:09 singlevm ciao-controller[23771]: main.(*controller).CreateServer(0xc4200e0af0, 0xc4206183c6, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42057fbc0, ...)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /home/runner/test/src/github.com/ciao-project/ciao/ciao-controller/compute.go:380 +0x366
Nov 07 15:15:09 singlevm ciao-controller[23771]: github.com/ciao-project/ciao/ciao-controller/api.createInstance(0xc4202b2a00, 0xe1be60, 0xc4200f17a0, 0xc42062a300, 0x1f, 0xc420521530, 0x30, 0x30, 0x967460)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /home/runner/test/src/github.com/ciao-project/ciao/ciao-controller/api/api.go:1182 +0x1bd
Nov 07 15:15:09 singlevm ciao-controller[23771]: github.com/ciao-project/ciao/ciao-controller/api.Handler.ServeHTTP(0xc4202b2a00, 0x9c4580, 0xe1c600, 0xe1be60, 0xc4200f17a0, 0xc42062a300)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /home/runner/test/src/github.com/ciao-project/ciao/ciao-controller/api/api.go:269 +0xfd
Nov 07 15:15:09 singlevm ciao-controller[23771]: github.com/ciao-project/ciao/ciao-controller/api.(*Handler).ServeHTTP(0xc4204c26a0, 0xe1be60, 0xc4200f17a0, 0xc42062a300)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         <autogenerated>:1 +0x6b
Nov 07 15:15:09 singlevm ciao-controller[23771]: main.(*clientCertAuthHandler).ServeHTTP(0xc4204ea5b0, 0xe1be60, 0xc4200f17a0, 0xc42062a100)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /home/runner/test/src/github.com/ciao-project/ciao/ciao-controller/server.go:72 +0x25c
Nov 07 15:15:09 singlevm ciao-controller[23771]: github.com/ciao-project/ciao/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202308c0, 0xe1be60, 0xc4200f17a0, 0xc42062a100)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /home/runner/test/src/github.com/ciao-project/ciao/vendor/github.com/gorilla/mux/mux.go:114 +0xdc
Nov 07 15:15:09 singlevm ciao-controller[23771]: net/http.serverHandler.ServeHTTP(0xc4202801a0, 0xe1be60, 0xc4200f17a0, 0xc4205c3f00)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /usr/local/go/src/net/http/server.go:2619 +0xb4
Nov 07 15:15:09 singlevm ciao-controller[23771]: net/http.(*conn).serve(0xc4204baf00, 0xe1c560, 0xc42015e500)
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /usr/local/go/src/net/http/server.go:1801 +0x71d
Nov 07 15:15:09 singlevm ciao-controller[23771]: created by net/http.(*Server).Serve
Nov 07 15:15:09 singlevm ciao-controller[23771]:         /usr/local/go/src/net/http/server.go:2720 +0x288

```

**Comment by rbradford** [comment]
@markdryan  is this the crash you just fixed in #1600 ?
